language: java
jdk:
  - openjdk15

sudo: false

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      max86ts@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

  # Start PostgreSQL
services:
  - postgresql

  # Create a database
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

env:
  global:
    - CODECOV_TOKEN=17727cce-97c3-49d1-a841-4d35aa9256ea
